apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-wa-deployment
spec:
  replicas: 6 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: news-wa
  template:
    metadata:
      labels:
        app: news-wa
    spec:
      containers:
        - name: news-wa
          image: yash5090/news-wa:latest # Replace with the actual image tag
          ports:
            - containerPort: 3000 # Replace with the port your Tetris game listens on
